// The vendored design system: fetch it, and prove it has not drifted.
//
// telecraft-dev/telecraft authors the tokens, the base sheet and the faces.
// This repository holds copies. ADR-0047's consequences say that dependency
// should be "a versioned release, not a copy", and there is no release to
// depend on: the tagging scheme is telecraft-dev/telecraft#86 and is being
// decided elsewhere. Inventing one here would put a second answer in front
// of that decision, so this file does the smaller honest thing instead —
// it writes down where every copy came from and fails when the copy and the
// source disagree. Drift made visible is what a copy can offer. It is not a
// release, and `tools/vendored.json` says so in its own words.
//
//   node tools/vendor.mjs check           verify every copy
//   node tools/vendor.mjs update [ref]    refetch every copy at `ref`
//
// A `.css` copy carries a provenance header, prepended, so that a person
// who opens the file learns where it came from before they edit it by
// mistake. Everything else — the faces, the licences, the mark — is byte
// for byte what upstream holds, because a woff2 cannot carry a comment.
// The check therefore requires a text copy to *end* with the upstream bytes
// and to name the recorded commit in its header, which needs no parsing and
// cannot be fooled by reformatting the header.

import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import process from 'node:process'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const manifestPath = join(root, 'tools', 'vendored.json')

const digest = (bytes) => createHash('sha256').update(bytes).digest('hex')

async function fetchRaw(manifest, ref, from) {
  const url = `${manifest.raw}/${ref}/${from}`
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`${url} answered ${response.status} ${response.statusText}`)
  }
  return Buffer.from(await response.arrayBuffer())
}

/**
 * The header a text copy carries. It names the commit rather than the branch
 * because a branch moves and a commit does not, and a reader who wants to
 * know whether this file is current needs the thing that cannot have changed
 * underneath them.
 */
function header(manifest, file) {
  return [
    '/*',
    ' * VENDORED — do not edit this file here.',
    ' *',
    ` * Source:  ${manifest.repository}`,
    ` * Path:    ${file.from}`,
    ` * Commit:  ${manifest.commit}`,
    ` * Ref:     ${manifest.ref}`,
    ' *',
    ' * A copy, not a release. ADR-0047 asked for a versioned artefact and',
    ' * there is no versioning scheme yet (telecraft-dev/telecraft#86), so',
    ' * this is a copy whose provenance is written down and whose drift is',
    ' * checked: `node tools/vendor.mjs check`, and in CI on every pull',
    ' * request. Edit it upstream and refetch with',
    ' * `node tools/vendor.mjs update`.',
    ' */',
    '',
    '',
  ].join('\n')
}

const isText = (file) => file.to.endsWith('.css')

async function update(manifest, ref) {
  // Resolve the ref to the commit it points at now, so the header records a
  // thing that cannot move even though the ref can.
  const api = `https://api.github.com/repos/telecraft-dev/telecraft/commits/${ref}`
  const response = await fetch(api, { headers: { accept: 'application/vnd.github.sha' } })
  if (!response.ok) {
    throw new Error(`${api} answered ${response.status} ${response.statusText}`)
  }
  manifest.ref = ref
  manifest.commit = (await response.text()).trim()

  for (const file of manifest.files) {
    const upstream = await fetchRaw(manifest, manifest.commit, file.from)
    file.sha256 = digest(upstream)
    const body = isText(file)
      ? Buffer.concat([Buffer.from(header(manifest, file), 'utf8'), upstream])
      : upstream
    await writeFile(join(root, file.to), body)
    console.log(`updated ${file.to} (${upstream.length} bytes from ${file.from})`)
  }
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)
  console.log(`vendored ${manifest.files.length} files from ${ref} at ${manifest.commit}`)
}

async function check(manifest) {
  const problems = []
  const drift = []

  for (const file of manifest.files) {
    const local = await readFile(join(root, file.to))
    const upstream = await fetchRaw(manifest, manifest.commit, file.from)

    if (digest(upstream) !== file.sha256) {
      problems.push(`${file.to}: the recorded sha256 is not what ${file.from} holds at ${manifest.commit}`)
    }
    if (isText(file)) {
      // A text copy is the upstream bytes with a header in front of them, so
      // the tail must match exactly and the head must name the commit. No
      // parsing: reformatting the header cannot make the check pass or fail
      // for the wrong reason.
      const cut = Math.max(0, local.length - upstream.length)
      if (!local.subarray(cut).equals(upstream)) {
        problems.push(`${file.to}: does not end with ${file.from} as it stands at ${manifest.commit}`)
      }
      if (!local.subarray(0, cut).includes(manifest.commit)) {
        problems.push(`${file.to}: the provenance header does not name ${manifest.commit}`)
      }
    } else if (!local.equals(upstream)) {
      problems.push(`${file.to}: differs from ${file.from} at ${manifest.commit}`)
    }

    // Has the source moved on since? Fatal when the copies were taken from
    // the default branch, reported when they were taken from somewhere else,
    // because a copy of an unmerged branch is meant to differ from main.
    const onMain = await fetchRaw(manifest, 'main', file.from).catch(() => null)
    if (onMain === null) {
      drift.push(`${file.from} does not exist on main`)
    } else if (digest(onMain) !== file.sha256) {
      drift.push(`${file.from} has changed on main since ${manifest.commit}`)
    }
  }

  const pinnedToMain = manifest.ref === 'main'
  if (drift.length > 0 && pinnedToMain) problems.push(...drift)

  if (problems.length > 0) {
    console.error('vendor check failed: the design system copies and their source disagree.')
    for (const problem of problems) console.error(`  ${problem}`)
    console.error('\nRefetch with `node tools/vendor.mjs update` and commit the result.')
    process.exit(1)
  }

  if (drift.length > 0) {
    console.log(`vendor check: interim state — ${manifest.interim}`)
    console.log(`  \`ref\` is ${manifest.ref}, not main, so these are reported and not failed:`)
    for (const item of drift) console.log(`    ${item}`)
    console.log('  Point `ref` at main once the source lands, and drift becomes fatal again.')
  }
  console.log(
    `vendor check passed: ${manifest.files.length} copies match ${manifest.ref} at ${manifest.commit}`,
  )
}

const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
const [command, ref] = process.argv.slice(2)
if (command === 'update') await update(manifest, ref ?? manifest.ref)
else if (command === 'check' || command === undefined) await check(manifest)
else {
  console.error('usage: node tools/vendor.mjs [check|update [ref]]')
  process.exit(2)
}
